---
steps:
  - bash: |
      set -euo pipefail
      brew install meson doxygen bison
      brew link bison --force
    displayName: 'Dependencies (macOS)'
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
