---
steps:
  - bash: |
      set -euo pipefail
      python -m pip install --upgrade pip meson
      sudo apt update -y
      sudo env DEBIAN_FRONTEND=noninteractive apt install -y \
        doxygen libxcb-xkb-dev valgrind ninja-build \
        libwayland-dev wayland-protocols bison graphviz
    displayName: 'Dependencies (GNU/Linux)'
